version : '3.7'

services:
    nginx:
        container_name: nginx
        build: srcs/nginx
        ports:
            - '9000'
            - '443'
        volumes:
            - ./srcs/nginx.conf:/etc/nginx/nginx.conf
            - ./srcs/ssl:/etc/ssl
            - ./srcs/www:/var/www
        env_file:
            - path: .env
        restart : unless-stopped
        networks:
            - inception

    wordpress:
        container_name: wordpress
        build: srcs/wordpress
        ports:
            - '9000'
        depends_on:
            - mariadb
        volumes:
            - wordpress:/var/www/html
        env_file:
            - path: .env
        restart : unless-stopped
        networks:
            - inception

    mariadb:
        container_name: mariadb
        build: srcs/mariadb
        ports:
            - '3306'
        env_file:
            - path: .env
        volumes:
            - mariadb:/var/lib/mysql
        restart : unless-stopped
        networks:
            - inception

volumes:
    mariadb:
        name: mariadb
        driver: local
        device: '/home/ofadhel/data/mariadb'
    wordpress:
        name: wordpress
        driver: local
        device: '/home/ofadhel/data/wordpress'

networks:
    inception:
        ipam:
            driver: default

