services:
    nginx:
        image: nginx:latest
        deploy:
            replicas: 3
            resources:
                limits:
                    cpus: "0.1"
                    memory: 50M
            restart_policy:
                condition: on-failure
        ports:
            - "80:80"
            - "443:443"
        networks:
            - inception
        configs:
            - source: httpd-config
              target: /etc/nginx/conf.d/default.conf
        secrets:
            - server-certificate
    wordpress:
        image: wordpress:latest
        deploy:
            replicas: 3
            resources:
                limits:
                    cpus: "0.1"
                    memory: 50M
            restart_policy:
                condition: on-failure
        environment:
            WORDPRESS_DB_HOST: mariadb
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: password
            WORDPRESS_DB_NAME: wordpress
        volumes:
            - wordpress:/var/www/html
        ports:
            - "8080:80"
        networks:
            - inception
        configs:
            - source: httpd-config
              target: /etc/apache2/sites-available/000-default.conf
        secrets:
            - server-certificate
    mariadb:
        image: mariadb:latest
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.1"
                    memory: 50M
            restart_policy:
                condition: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: wordpress
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - inception
    ftp:
        image: fauria/vsftpd
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.1"
                    memory: 50M
            restart_policy:
                condition: on-failure
        environment:
            FTP_USER: user
            FTP_PASS: password
        ports:
            - "21:21"
        volumes:
            - ftp:/home/vsftpd
        networks:
            - inception

volumes:
    mariadb:
        name: mariadb
        driver: local
    wordpress:
        name: wordpress
        driver: local

networks:
  inception:

