version : '3.7'

services:
    nginx:
        container_name: nginx
        image: nginx:42
        build: requirements/nginx
        depends_on:
            - wordpress
        ports:
            - '443:443'
        volumes:
            - wordpress:/var/www/html
        env_file:
            - .env
        restart : always
        networks:
            - inception

    mariadb:
        container_name: mariadb
        image: mariadb:42
        build: requirements/mariadb
        env_file:
            - .env
        volumes:
            - mariadb:/var/lib/mysql
        restart : always
        networks:
            - inception

    wordpress:
        container_name: wordpress
        image: wordpress:6.4.3
        build: requirements/wordpress
        depends_on:
            - mariadb
        volumes:
            - wordpress:/var/www/html
        env_file:
            - .env
        restart : always
        networks:
            - inception

volumes:
    mariadb:
        driver: local
        driver_opts:
            type: none
            device: '/home/fazzel/data/mariadb'
            o: bind
    wordpress:
        driver: local
        driver_opts:
            type: none
            device: '/home/fazzel/data/wordpress'
            o: bind

networks:
    inception:
        name: inception
