version : '3.7'

services:
    nginx:
        image: ./srcs/nginx
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./srcs/nginx.conf:/etc/nginx/nginx.conf
            - ./srcs/ssl:/etc/ssl
            - ./srcs/www:/var/www
        networks:
            - inception

    wordpress:
        image: ./srcs/wordpress
        ports:
            - "80:80"
        volumes:
            - wordpress:/var/www/html
        env_file:
            - path: ./.env
        networks:
            - inception

    mariadb:
        image: ./srcs/mariadb
        env_file:
            - path: ./.env
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - inception

volumes:
    mariadb:
        name: mariadb
        driver: local
    wordpress:
        name: wordpress
        driver: local\


networks:
    inception:

