version : '3.7'

services:
    nginx:
        container_name: nginx
        build: requirements/nginx
        depends_on:
            - wordpress
        ports:
            - '443:443'
        volumes:
            - wordpress:/var/www/html
        env_file:
            - .env
        restart : unless-stopped
        networks:
            - inception

    mariadb:
        container_name: mariadb
        build: requirements/mariadb
        env_file:
            - .env
        volumes:
            - mariadb:/var/lib/mysql
        restart : unless-stopped
        networks:
            - inception

    wordpress:
        container_name: wordpress
        build: requirements/wordpress
        depends_on:
            - mariadb
        volumes:
            - wordpress:/var/www/html
        env_file:
            - .env
        restart : unless-stopped
        networks:
            - inception

volumes:
    mariadb:
        name: mariadb
        driver: local
        driver_opts:
            device: '/home/user_to_change/data/mariadb'
            o: bind
            type: none
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            device: '/home/user_to_change/data/wordpress'
            o: bind
            type: none

networks:
    inception:
        name: inception
